using DNX.Extensions.Maths;
using DNX.Extensions.Maths.BuiltInTypes;
using DNX.Extensions.Tests.Maths.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Tests.Maths.BuiltInTypes;

public class MathsDecimalExtensionsTests
{
    [Theory]
    [MemberData(nameof(MathsDecimalExtensionsTestsDataSource.IsBetween_Default), MemberType = typeof(MathsDecimalExtensionsTestsDataSource))]
    public void IsBetween_Default(decimal value, decimal min, decimal max, bool expectedResult)
    {
        value.IsBetween(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDecimalExtensionsTestsDataSource.IsBetween_BoundsType), MemberType = typeof(MathsDecimalExtensionsTestsDataSource))]
    public void IsBetween_BoundsType(decimal value, decimal min, decimal max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDecimalExtensionsTestsDataSource.IsBetweenEither_Default), MemberType = typeof(MathsDecimalExtensionsTestsDataSource))]
    public void IsBetweenEither_Default(decimal value, decimal min, decimal max, bool expectedResult)
    {
        value.IsBetweenEither(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDecimalExtensionsTestsDataSource.IsBetweenEither_BoundsType), MemberType = typeof(MathsDecimalExtensionsTestsDataSource))]
    public void IsBetweenEither_BoundsType(decimal value, decimal min, decimal max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetweenEither(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDecimalExtensionsTestsDataSource.IsBetween), MemberType = typeof(MathsDecimalExtensionsTestsDataSource))]
    public void IsBetween(decimal value, decimal min, decimal max, bool allowEitherOrder, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, allowEitherOrder, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDecimalExtensionsTestsDataSource.GetLowerBound_Default), MemberType = typeof(MathsDecimalExtensionsTestsDataSource))]
    public void GetLowerBound_Default(decimal min, decimal max, decimal expectedResult)
    {
        MathsDecimalExtensions.GetLowerBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDecimalExtensionsTestsDataSource.GetLowerBound_AllowEitherOrder), MemberType = typeof(MathsDecimalExtensionsTestsDataSource))]
    public void GetLowerBound_AllowEitherOrder(decimal min, decimal max, bool allowEitherOrder, decimal expectedResult)
    {
        MathsDecimalExtensions.GetLowerBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDecimalExtensionsTestsDataSource.GetUpperBound_Default), MemberType = typeof(MathsDecimalExtensionsTestsDataSource))]
    public void GetUpperBound_Default(decimal min, decimal max, decimal expectedResult)
    {
        MathsDecimalExtensions.GetUpperBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDecimalExtensionsTestsDataSource.GetUpperBound_AllowEitherOrder), MemberType = typeof(MathsDecimalExtensionsTestsDataSource))]
    public void GetUpperBound_AllowEitherOrder(decimal min, decimal max, bool allowEitherOrder, decimal expectedResult)
    {
        MathsDecimalExtensions.GetUpperBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }
}

