using DNX.Extensions.Maths;
using DNX.Extensions.Maths.BuiltInTypes;
using DNX.Extensions.Tests.Maths.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Tests.Maths.BuiltInTypes;

public class MathsSByteExtensionsTests
{
    [Theory]
    [MemberData(nameof(MathsSByteExtensionsTestsDataSource.IsBetween_Default), MemberType = typeof(MathsSByteExtensionsTestsDataSource))]
    public void IsBetween_Default(sbyte value, sbyte min, sbyte max, bool expectedResult)
    {
        value.IsBetween(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsSByteExtensionsTestsDataSource.IsBetween_BoundsType), MemberType = typeof(MathsSByteExtensionsTestsDataSource))]
    public void IsBetween_BoundsType(sbyte value, sbyte min, sbyte max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsSByteExtensionsTestsDataSource.IsBetweenEither_Default), MemberType = typeof(MathsSByteExtensionsTestsDataSource))]
    public void IsBetweenEither_Default(sbyte value, sbyte min, sbyte max, bool expectedResult)
    {
        value.IsBetweenEither(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsSByteExtensionsTestsDataSource.IsBetweenEither_BoundsType), MemberType = typeof(MathsSByteExtensionsTestsDataSource))]
    public void IsBetweenEither_BoundsType(sbyte value, sbyte min, sbyte max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetweenEither(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsSByteExtensionsTestsDataSource.IsBetween), MemberType = typeof(MathsSByteExtensionsTestsDataSource))]
    public void IsBetween(sbyte value, sbyte min, sbyte max, bool allowEitherOrder, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, allowEitherOrder, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsSByteExtensionsTestsDataSource.GetLowerBound_Default), MemberType = typeof(MathsSByteExtensionsTestsDataSource))]
    public void GetLowerBound_Default(sbyte min, sbyte max, sbyte expectedResult)
    {
        MathsSByteExtensions.GetLowerBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsSByteExtensionsTestsDataSource.GetLowerBound_AllowEitherOrder), MemberType = typeof(MathsSByteExtensionsTestsDataSource))]
    public void GetLowerBound_AllowEitherOrder(sbyte min, sbyte max, bool allowEitherOrder, sbyte expectedResult)
    {
        MathsSByteExtensions.GetLowerBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsSByteExtensionsTestsDataSource.GetUpperBound_Default), MemberType = typeof(MathsSByteExtensionsTestsDataSource))]
    public void GetUpperBound_Default(sbyte min, sbyte max, sbyte expectedResult)
    {
        MathsSByteExtensions.GetUpperBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsSByteExtensionsTestsDataSource.GetUpperBound_AllowEitherOrder), MemberType = typeof(MathsSByteExtensionsTestsDataSource))]
    public void GetUpperBound_AllowEitherOrder(sbyte min, sbyte max, bool allowEitherOrder, sbyte expectedResult)
    {
        MathsSByteExtensions.GetUpperBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }
}

