using DNX.Extensions.Maths;
using DNX.Extensions.Maths.BuiltInTypes;
using DNX.Extensions.Tests.Maths.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Tests.Maths.BuiltInTypes;

public class MathsInt32ExtensionsTests
{
    [Theory]
    [MemberData(nameof(MathsInt32ExtensionsTestsDataSource.IsBetween_Default), MemberType = typeof(MathsInt32ExtensionsTestsDataSource))]
    public void IsBetween_Default(int value, int min, int max, bool expectedResult)
    {
        value.IsBetween(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt32ExtensionsTestsDataSource.IsBetween_BoundsType), MemberType = typeof(MathsInt32ExtensionsTestsDataSource))]
    public void IsBetween_BoundsType(int value, int min, int max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt32ExtensionsTestsDataSource.IsBetweenEither_Default), MemberType = typeof(MathsInt32ExtensionsTestsDataSource))]
    public void IsBetweenEither_Default(int value, int min, int max, bool expectedResult)
    {
        value.IsBetweenEither(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt32ExtensionsTestsDataSource.IsBetweenEither_BoundsType), MemberType = typeof(MathsInt32ExtensionsTestsDataSource))]
    public void IsBetweenEither_BoundsType(int value, int min, int max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetweenEither(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt32ExtensionsTestsDataSource.IsBetween), MemberType = typeof(MathsInt32ExtensionsTestsDataSource))]
    public void IsBetween(int value, int min, int max, bool allowEitherOrder, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, allowEitherOrder, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt32ExtensionsTestsDataSource.GetLowerBound_Default), MemberType = typeof(MathsInt32ExtensionsTestsDataSource))]
    public void GetLowerBound_Default(int min, int max, int expectedResult)
    {
        MathsInt32Extensions.GetLowerBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt32ExtensionsTestsDataSource.GetLowerBound_AllowEitherOrder), MemberType = typeof(MathsInt32ExtensionsTestsDataSource))]
    public void GetLowerBound_AllowEitherOrder(int min, int max, bool allowEitherOrder, int expectedResult)
    {
        MathsInt32Extensions.GetLowerBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt32ExtensionsTestsDataSource.GetUpperBound_Default), MemberType = typeof(MathsInt32ExtensionsTestsDataSource))]
    public void GetUpperBound_Default(int min, int max, int expectedResult)
    {
        MathsInt32Extensions.GetUpperBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt32ExtensionsTestsDataSource.GetUpperBound_AllowEitherOrder), MemberType = typeof(MathsInt32ExtensionsTestsDataSource))]
    public void GetUpperBound_AllowEitherOrder(int min, int max, bool allowEitherOrder, int expectedResult)
    {
        MathsInt32Extensions.GetUpperBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }
}

