using DNX.Extensions.Maths;
using DNX.Extensions.Maths.BuiltInTypes;
using DNX.Extensions.Tests.Maths.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Tests.Maths.BuiltInTypes;

public class MathsDoubleExtensionsTests
{
    [Theory]
    [MemberData(nameof(MathsDoubleExtensionsTestsDataSource.IsBetween_Default), MemberType = typeof(MathsDoubleExtensionsTestsDataSource))]
    public void IsBetween_Default(double value, double min, double max, bool expectedResult)
    {
        value.IsBetween(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDoubleExtensionsTestsDataSource.IsBetween_BoundsType), MemberType = typeof(MathsDoubleExtensionsTestsDataSource))]
    public void IsBetween_BoundsType(double value, double min, double max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDoubleExtensionsTestsDataSource.IsBetweenEither_Default), MemberType = typeof(MathsDoubleExtensionsTestsDataSource))]
    public void IsBetweenEither_Default(double value, double min, double max, bool expectedResult)
    {
        value.IsBetweenEither(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDoubleExtensionsTestsDataSource.IsBetweenEither_BoundsType), MemberType = typeof(MathsDoubleExtensionsTestsDataSource))]
    public void IsBetweenEither_BoundsType(double value, double min, double max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetweenEither(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDoubleExtensionsTestsDataSource.IsBetween), MemberType = typeof(MathsDoubleExtensionsTestsDataSource))]
    public void IsBetween(double value, double min, double max, bool allowEitherOrder, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, allowEitherOrder, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDoubleExtensionsTestsDataSource.GetLowerBound_Default), MemberType = typeof(MathsDoubleExtensionsTestsDataSource))]
    public void GetLowerBound_Default(double min, double max, double expectedResult)
    {
        MathsDoubleExtensions.GetLowerBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDoubleExtensionsTestsDataSource.GetLowerBound_AllowEitherOrder), MemberType = typeof(MathsDoubleExtensionsTestsDataSource))]
    public void GetLowerBound_AllowEitherOrder(double min, double max, bool allowEitherOrder, double expectedResult)
    {
        MathsDoubleExtensions.GetLowerBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDoubleExtensionsTestsDataSource.GetUpperBound_Default), MemberType = typeof(MathsDoubleExtensionsTestsDataSource))]
    public void GetUpperBound_Default(double min, double max, double expectedResult)
    {
        MathsDoubleExtensions.GetUpperBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsDoubleExtensionsTestsDataSource.GetUpperBound_AllowEitherOrder), MemberType = typeof(MathsDoubleExtensionsTestsDataSource))]
    public void GetUpperBound_AllowEitherOrder(double min, double max, bool allowEitherOrder, double expectedResult)
    {
        MathsDoubleExtensions.GetUpperBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }
}

