using DNX.Extensions.Maths;
using DNX.Extensions.Maths.BuiltInTypes;
using DNX.Extensions.Tests.Maths.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Tests.Maths.BuiltInTypes;

public class MathsInt64ExtensionsTests
{
    [Theory]
    [MemberData(nameof(MathsInt64ExtensionsTestsDataSource.IsBetween_Default), MemberType = typeof(MathsInt64ExtensionsTestsDataSource))]
    public void IsBetween_Default(long value, long min, long max, bool expectedResult)
    {
        value.IsBetween(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt64ExtensionsTestsDataSource.IsBetween_BoundsType), MemberType = typeof(MathsInt64ExtensionsTestsDataSource))]
    public void IsBetween_BoundsType(long value, long min, long max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt64ExtensionsTestsDataSource.IsBetweenEither_Default), MemberType = typeof(MathsInt64ExtensionsTestsDataSource))]
    public void IsBetweenEither_Default(long value, long min, long max, bool expectedResult)
    {
        value.IsBetweenEither(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt64ExtensionsTestsDataSource.IsBetweenEither_BoundsType), MemberType = typeof(MathsInt64ExtensionsTestsDataSource))]
    public void IsBetweenEither_BoundsType(long value, long min, long max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetweenEither(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt64ExtensionsTestsDataSource.IsBetween), MemberType = typeof(MathsInt64ExtensionsTestsDataSource))]
    public void IsBetween(long value, long min, long max, bool allowEitherOrder, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, allowEitherOrder, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt64ExtensionsTestsDataSource.GetLowerBound_Default), MemberType = typeof(MathsInt64ExtensionsTestsDataSource))]
    public void GetLowerBound_Default(long min, long max, long expectedResult)
    {
        MathsInt64Extensions.GetLowerBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt64ExtensionsTestsDataSource.GetLowerBound_AllowEitherOrder), MemberType = typeof(MathsInt64ExtensionsTestsDataSource))]
    public void GetLowerBound_AllowEitherOrder(long min, long max, bool allowEitherOrder, long expectedResult)
    {
        MathsInt64Extensions.GetLowerBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt64ExtensionsTestsDataSource.GetUpperBound_Default), MemberType = typeof(MathsInt64ExtensionsTestsDataSource))]
    public void GetUpperBound_Default(long min, long max, long expectedResult)
    {
        MathsInt64Extensions.GetUpperBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsInt64ExtensionsTestsDataSource.GetUpperBound_AllowEitherOrder), MemberType = typeof(MathsInt64ExtensionsTestsDataSource))]
    public void GetUpperBound_AllowEitherOrder(long min, long max, bool allowEitherOrder, long expectedResult)
    {
        MathsInt64Extensions.GetUpperBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }
}

