using DNX.Extensions.Maths;
using DNX.Extensions.Maths.BuiltInTypes;
using DNX.Extensions.Tests.Maths.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Tests.Maths.BuiltInTypes;

public class MathsGuidExtensionsTests
{
    [Theory]
    [MemberData(nameof(MathsGuidExtensionsTestsDataSource.IsBetween_Default), MemberType = typeof(MathsGuidExtensionsTestsDataSource))]
    public void IsBetween_Default(Guid value, Guid min, Guid max, bool expectedResult)
    {
        value.IsBetween(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsGuidExtensionsTestsDataSource.IsBetween_BoundsType), MemberType = typeof(MathsGuidExtensionsTestsDataSource))]
    public void IsBetween_BoundsType(Guid value, Guid min, Guid max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsGuidExtensionsTestsDataSource.IsBetweenEither_Default), MemberType = typeof(MathsGuidExtensionsTestsDataSource))]
    public void IsBetweenEither_Default(Guid value, Guid min, Guid max, bool expectedResult)
    {
        value.IsBetweenEither(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsGuidExtensionsTestsDataSource.IsBetweenEither_BoundsType), MemberType = typeof(MathsGuidExtensionsTestsDataSource))]
    public void IsBetweenEither_BoundsType(Guid value, Guid min, Guid max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetweenEither(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsGuidExtensionsTestsDataSource.IsBetween), MemberType = typeof(MathsGuidExtensionsTestsDataSource))]
    public void IsBetween(Guid value, Guid min, Guid max, bool allowEitherOrder, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, allowEitherOrder, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsGuidExtensionsTestsDataSource.GetLowerBound_Default), MemberType = typeof(MathsGuidExtensionsTestsDataSource))]
    public void GetLowerBound_Default(Guid min, Guid max, Guid expectedResult)
    {
        MathsGuidExtensions.GetLowerBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsGuidExtensionsTestsDataSource.GetLowerBound_AllowEitherOrder), MemberType = typeof(MathsGuidExtensionsTestsDataSource))]
    public void GetLowerBound_AllowEitherOrder(Guid min, Guid max, bool allowEitherOrder, Guid expectedResult)
    {
        MathsGuidExtensions.GetLowerBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsGuidExtensionsTestsDataSource.GetUpperBound_Default), MemberType = typeof(MathsGuidExtensionsTestsDataSource))]
    public void GetUpperBound_Default(Guid min, Guid max, Guid expectedResult)
    {
        MathsGuidExtensions.GetUpperBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsGuidExtensionsTestsDataSource.GetUpperBound_AllowEitherOrder), MemberType = typeof(MathsGuidExtensionsTestsDataSource))]
    public void GetUpperBound_AllowEitherOrder(Guid min, Guid max, bool allowEitherOrder, Guid expectedResult)
    {
        MathsGuidExtensions.GetUpperBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }
}

