using DNX.Extensions.Maths;
using DNX.Extensions.Maths.BuiltInTypes;
using DNX.Extensions.Tests.Maths.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Tests.Maths.BuiltInTypes;

public class MathsUInt16ExtensionsTests
{
    [Theory]
    [MemberData(nameof(MathsUInt16ExtensionsTestsDataSource.IsBetween_Default), MemberType = typeof(MathsUInt16ExtensionsTestsDataSource))]
    public void IsBetween_Default(ushort value, ushort min, ushort max, bool expectedResult)
    {
        value.IsBetween(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt16ExtensionsTestsDataSource.IsBetween_BoundsType), MemberType = typeof(MathsUInt16ExtensionsTestsDataSource))]
    public void IsBetween_BoundsType(ushort value, ushort min, ushort max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt16ExtensionsTestsDataSource.IsBetweenEither_Default), MemberType = typeof(MathsUInt16ExtensionsTestsDataSource))]
    public void IsBetweenEither_Default(ushort value, ushort min, ushort max, bool expectedResult)
    {
        value.IsBetweenEither(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt16ExtensionsTestsDataSource.IsBetweenEither_BoundsType), MemberType = typeof(MathsUInt16ExtensionsTestsDataSource))]
    public void IsBetweenEither_BoundsType(ushort value, ushort min, ushort max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetweenEither(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt16ExtensionsTestsDataSource.IsBetween), MemberType = typeof(MathsUInt16ExtensionsTestsDataSource))]
    public void IsBetween(ushort value, ushort min, ushort max, bool allowEitherOrder, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, allowEitherOrder, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt16ExtensionsTestsDataSource.GetLowerBound_Default), MemberType = typeof(MathsUInt16ExtensionsTestsDataSource))]
    public void GetLowerBound_Default(ushort min, ushort max, ushort expectedResult)
    {
        MathsUInt16Extensions.GetLowerBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt16ExtensionsTestsDataSource.GetLowerBound_AllowEitherOrder), MemberType = typeof(MathsUInt16ExtensionsTestsDataSource))]
    public void GetLowerBound_AllowEitherOrder(ushort min, ushort max, bool allowEitherOrder, ushort expectedResult)
    {
        MathsUInt16Extensions.GetLowerBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt16ExtensionsTestsDataSource.GetUpperBound_Default), MemberType = typeof(MathsUInt16ExtensionsTestsDataSource))]
    public void GetUpperBound_Default(ushort min, ushort max, ushort expectedResult)
    {
        MathsUInt16Extensions.GetUpperBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt16ExtensionsTestsDataSource.GetUpperBound_AllowEitherOrder), MemberType = typeof(MathsUInt16ExtensionsTestsDataSource))]
    public void GetUpperBound_AllowEitherOrder(ushort min, ushort max, bool allowEitherOrder, ushort expectedResult)
    {
        MathsUInt16Extensions.GetUpperBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }
}

