using DNX.Extensions.Maths;
using DNX.Extensions.Maths.BuiltInTypes;
using DNX.Extensions.Tests.Maths.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Tests.Maths.BuiltInTypes;

public class MathsFloatExtensionsTests
{
    [Theory]
    [MemberData(nameof(MathsFloatExtensionsTestsDataSource.IsBetween_Default), MemberType = typeof(MathsFloatExtensionsTestsDataSource))]
    public void IsBetween_Default(float value, float min, float max, bool expectedResult)
    {
        value.IsBetween(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsFloatExtensionsTestsDataSource.IsBetween_BoundsType), MemberType = typeof(MathsFloatExtensionsTestsDataSource))]
    public void IsBetween_BoundsType(float value, float min, float max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsFloatExtensionsTestsDataSource.IsBetweenEither_Default), MemberType = typeof(MathsFloatExtensionsTestsDataSource))]
    public void IsBetweenEither_Default(float value, float min, float max, bool expectedResult)
    {
        value.IsBetweenEither(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsFloatExtensionsTestsDataSource.IsBetweenEither_BoundsType), MemberType = typeof(MathsFloatExtensionsTestsDataSource))]
    public void IsBetweenEither_BoundsType(float value, float min, float max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetweenEither(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsFloatExtensionsTestsDataSource.IsBetween), MemberType = typeof(MathsFloatExtensionsTestsDataSource))]
    public void IsBetween(float value, float min, float max, bool allowEitherOrder, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, allowEitherOrder, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsFloatExtensionsTestsDataSource.GetLowerBound_Default), MemberType = typeof(MathsFloatExtensionsTestsDataSource))]
    public void GetLowerBound_Default(float min, float max, float expectedResult)
    {
        MathsFloatExtensions.GetLowerBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsFloatExtensionsTestsDataSource.GetLowerBound_AllowEitherOrder), MemberType = typeof(MathsFloatExtensionsTestsDataSource))]
    public void GetLowerBound_AllowEitherOrder(float min, float max, bool allowEitherOrder, float expectedResult)
    {
        MathsFloatExtensions.GetLowerBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsFloatExtensionsTestsDataSource.GetUpperBound_Default), MemberType = typeof(MathsFloatExtensionsTestsDataSource))]
    public void GetUpperBound_Default(float min, float max, float expectedResult)
    {
        MathsFloatExtensions.GetUpperBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsFloatExtensionsTestsDataSource.GetUpperBound_AllowEitherOrder), MemberType = typeof(MathsFloatExtensionsTestsDataSource))]
    public void GetUpperBound_AllowEitherOrder(float min, float max, bool allowEitherOrder, float expectedResult)
    {
        MathsFloatExtensions.GetUpperBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }
}

