using DNX.Extensions.Maths;
using DNX.Extensions.Maths.BuiltInTypes;
using DNX.Extensions.Tests.Maths.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Tests.Maths.BuiltInTypes;

public class MathsUInt64ExtensionsTests
{
    [Theory]
    [MemberData(nameof(MathsUInt64ExtensionsTestsDataSource.IsBetween_Default), MemberType = typeof(MathsUInt64ExtensionsTestsDataSource))]
    public void IsBetween_Default(ulong value, ulong min, ulong max, bool expectedResult)
    {
        value.IsBetween(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt64ExtensionsTestsDataSource.IsBetween_BoundsType), MemberType = typeof(MathsUInt64ExtensionsTestsDataSource))]
    public void IsBetween_BoundsType(ulong value, ulong min, ulong max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt64ExtensionsTestsDataSource.IsBetweenEither_Default), MemberType = typeof(MathsUInt64ExtensionsTestsDataSource))]
    public void IsBetweenEither_Default(ulong value, ulong min, ulong max, bool expectedResult)
    {
        value.IsBetweenEither(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt64ExtensionsTestsDataSource.IsBetweenEither_BoundsType), MemberType = typeof(MathsUInt64ExtensionsTestsDataSource))]
    public void IsBetweenEither_BoundsType(ulong value, ulong min, ulong max, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetweenEither(min, max, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt64ExtensionsTestsDataSource.IsBetween), MemberType = typeof(MathsUInt64ExtensionsTestsDataSource))]
    public void IsBetween(ulong value, ulong min, ulong max, bool allowEitherOrder, IsBetweenBoundsType boundsType, bool expectedResult)
    {
        value.IsBetween(min, max, allowEitherOrder, boundsType).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt64ExtensionsTestsDataSource.GetLowerBound_Default), MemberType = typeof(MathsUInt64ExtensionsTestsDataSource))]
    public void GetLowerBound_Default(ulong min, ulong max, ulong expectedResult)
    {
        MathsUInt64Extensions.GetLowerBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt64ExtensionsTestsDataSource.GetLowerBound_AllowEitherOrder), MemberType = typeof(MathsUInt64ExtensionsTestsDataSource))]
    public void GetLowerBound_AllowEitherOrder(ulong min, ulong max, bool allowEitherOrder, ulong expectedResult)
    {
        MathsUInt64Extensions.GetLowerBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt64ExtensionsTestsDataSource.GetUpperBound_Default), MemberType = typeof(MathsUInt64ExtensionsTestsDataSource))]
    public void GetUpperBound_Default(ulong min, ulong max, ulong expectedResult)
    {
        MathsUInt64Extensions.GetUpperBound(min, max).ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(MathsUInt64ExtensionsTestsDataSource.GetUpperBound_AllowEitherOrder), MemberType = typeof(MathsUInt64ExtensionsTestsDataSource))]
    public void GetUpperBound_AllowEitherOrder(ulong min, ulong max, bool allowEitherOrder, ulong expectedResult)
    {
        MathsUInt64Extensions.GetUpperBound(min, max, allowEitherOrder).ShouldBe(expectedResult);
    }
}

