using System;
using DNX.Extensions.Exceptions;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Converters.BuiltInTypes;

/// <summary>
/// Class ConvertGuidExtensions.
/// </summary>
public static class ConvertGuidExtensions
{
    /// <summary>
    /// Converts the string to a Guid
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns>Guid</returns>
    /// <exception cref="DNX.Extensions.Exceptions.ConversionException">Unable to convert value to Type</exception>
    public static Guid ToGuid(this string text)
    {
        Guid result;

        if (!Guid.TryParse(text, out result))
        {
            throw new ConversionException(text, "Unable to convert value to Type", typeof(Guid));
        }

        return result;
    }

    /// <summary>
    /// Converts the string to a Guid, or returns the default value if the conversion fails
    /// </summary>
    /// <param name="text">The text.</param>
    /// <param name="defaultValue">The default value.</param>
    /// <returns>Guid</returns>
    public static Guid ToGuid(this string text, Guid defaultValue)
    {
        try
        {
            var result = text.ToGuid();

            return result;
        }
        catch (ConversionException)
        {
            return defaultValue;
        }
    }

    /// <summary>
    /// Determines if the string can be converted to a Guid or not
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns><c>true</c> if the specified text is a Guid; otherwise, <c>false</c>.</returns>
    public static bool IsGuid(this string text)
    {
        try
        {
            text.ToGuid();

            return true;
        }
        catch (ConversionException)
        {
            return false;
        }
    }
}

