using System;
using DNX.Extensions.Exceptions;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Converters.BuiltInTypes;

/// <summary>
/// Class ConvertDateTimeExtensions.
/// </summary>
public static class ConvertDateTimeExtensions
{
    /// <summary>
    /// Converts the string to a DateTime
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns>DateTime</returns>
    /// <exception cref="DNX.Extensions.Exceptions.ConversionException">Unable to convert value to Type</exception>
    public static DateTime ToDateTime(this string text)
    {
        DateTime result;

        if (!DateTime.TryParse(text, out result))
        {
            throw new ConversionException(text, "Unable to convert value to Type", typeof(DateTime));
        }

        return result;
    }

    /// <summary>
    /// Converts the string to a DateTime, or returns the default value if the conversion fails
    /// </summary>
    /// <param name="text">The text.</param>
    /// <param name="defaultValue">The default value.</param>
    /// <returns>DateTime</returns>
    public static DateTime ToDateTime(this string text, DateTime defaultValue)
    {
        try
        {
            var result = text.ToDateTime();

            return result;
        }
        catch (ConversionException)
        {
            return defaultValue;
        }
    }

    /// <summary>
    /// Determines if the string can be converted to a DateTime or not
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns><c>true</c> if the specified text is a DateTime; otherwise, <c>false</c>.</returns>
    public static bool IsDateTime(this string text)
    {
        try
        {
            text.ToDateTime();

            return true;
        }
        catch (ConversionException)
        {
            return false;
        }
    }
}

