using System;
using DNX.Extensions.Exceptions;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Converters.BuiltInTypes;

/// <summary>
/// Class ConvertUInt64Extensions.
/// </summary>
public static class ConvertUInt64Extensions
{
    /// <summary>
    /// Converts the string to a ulong
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns>ulong</returns>
    /// <exception cref="DNX.Extensions.Exceptions.ConversionException">Unable to convert value to Type</exception>
    public static ulong ToUInt64(this string text)
    {
        ulong result;

        if (!ulong.TryParse(text, out result))
        {
            throw new ConversionException(text, "Unable to convert value to Type", typeof(ulong));
        }

        return result;
    }

    /// <summary>
    /// Converts the string to a ulong, or returns the default value if the conversion fails
    /// </summary>
    /// <param name="text">The text.</param>
    /// <param name="defaultValue">The default value.</param>
    /// <returns>ulong</returns>
    public static ulong ToUInt64(this string text, ulong defaultValue)
    {
        try
        {
            var result = text.ToUInt64();

            return result;
        }
        catch (ConversionException)
        {
            return defaultValue;
        }
    }

    /// <summary>
    /// Determines if the string can be converted to a ulong or not
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns><c>true</c> if the specified text is a ulong; otherwise, <c>false</c>.</returns>
    public static bool IsUInt64(this string text)
    {
        try
        {
            text.ToUInt64();

            return true;
        }
        catch (ConversionException)
        {
            return false;
        }
    }
}

