using System;
using DNX.Extensions.Exceptions;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Converters.BuiltInTypes;

/// <summary>
/// Class ConvertSByteExtensions.
/// </summary>
public static class ConvertSByteExtensions
{
    /// <summary>
    /// Converts the string to a sbyte
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns>sbyte</returns>
    /// <exception cref="DNX.Extensions.Exceptions.ConversionException">Unable to convert value to SByte</exception>
    public static sbyte ToSByte(this string text)
    {
        sbyte result;

        if (!sbyte.TryParse(text, out result))
        {
            throw new ConversionException(text, "Unable to convert value to SByte", typeof(sbyte));
        }

        return result;
    }

    /// <summary>
    /// Converts the string to a sbyte, or returns the default value if the conversion fails
    /// </summary>
    /// <param name="text">The text.</param>
    /// <param name="defaultValue">The default value.</param>
    /// <returns>sbyte</returns>
    public static sbyte ToSByte(this string text, sbyte defaultValue)
    {
        try
        {
            var result = text.ToSByte();

            return result;
        }
        catch (ConversionException)
        {
            return defaultValue;
        }
    }

    /// <summary>
    /// Determines if the string can be converted to a sbyte or not
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns><c>true</c> if the specified text is a sbyte; otherwise, <c>false</c>.</returns>
    public static bool IsSByte(this string text)
    {
        try
        {
            text.ToSByte();

            return true;
        }
        catch (ConversionException)
        {
            return false;
        }
    }
}

