using System;
using DNX.Extensions.Exceptions;

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

namespace DNX.Extensions.Converters.BuiltInTypes;

/// <summary>
/// Class ConvertDoubleExtensions.
/// </summary>
public static class ConvertDoubleExtensions
{
    /// <summary>
    /// Converts the string to a double
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns>double</returns>
    /// <exception cref="DNX.Extensions.Exceptions.ConversionException">Unable to convert value to Type</exception>
    public static double ToDouble(this string text)
    {
        double result;

        if (!double.TryParse(text, out result))
        {
            throw new ConversionException(text, "Unable to convert value to Type", typeof(double));
        }

        return result;
    }

    /// <summary>
    /// Converts the string to a double, or returns the default value if the conversion fails
    /// </summary>
    /// <param name="text">The text.</param>
    /// <param name="defaultValue">The default value.</param>
    /// <returns>double</returns>
    public static double ToDouble(this string text, double defaultValue)
    {
        try
        {
            var result = text.ToDouble();

            return result;
        }
        catch (ConversionException)
        {
            return defaultValue;
        }
    }

    /// <summary>
    /// Determines if the string can be converted to a double or not
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns><c>true</c> if the specified text is a double; otherwise, <c>false</c>.</returns>
    public static bool IsDouble(this string text)
    {
        try
        {
            text.ToDouble();

            return true;
        }
        catch (ConversionException)
        {
            return false;
        }
    }
}

