#define ConversionExtensionsTestsDataSource_Decimal

//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

using System.Numerics;
using Xunit;

namespace DNX.Extensions.Tests.Conversion.BuiltInTypes.TestsDataSource;

public class ConversionDecimalExtensionsTestsDataSource
{
        private static readonly bool IsSigned = !(
                                            "decimal".StartsWith("U", StringComparison.OrdinalIgnoreCase)
                                            || "decimal".Equals("byte", StringComparison.OrdinalIgnoreCase)
                                            );
        private static readonly bool HasDecimalPlaces = (
                                            "decimal".Equals("float", StringComparison.OrdinalIgnoreCase)
                                            || "decimal".Equals("double", StringComparison.OrdinalIgnoreCase)
                                            || "decimal".Equals("decimal", StringComparison.OrdinalIgnoreCase)
                                            );
        private static readonly bool UsesExponentApproximations = !(
                                            "decimal".Equals("float", StringComparison.OrdinalIgnoreCase)
                                            || "decimal".Equals("double", StringComparison.OrdinalIgnoreCase)
                                            );

        private static decimal CreateValue(string text)
        {
            return decimal.Parse(text);
        }

#if ConversionExtensionsTestsDataSource_Guid
        private static readonly Guid Min_Guid = Guid.Empty;
        private static readonly Guid Max_Guid = Guid.Parse(Guid.Empty.ToString().Replace("0", "F"));
        private static readonly Guid Guid1 = Guid.NewGuid();
        private static readonly Guid Guid2 = Guid.NewGuid();

#endif

    public static TheoryData<string, bool> IsDecimal()
    {
        return new TheoryData<string, bool>()
        {
#if ConversionExtensionsTestsDataSource_Bool
            { "0", false },
            { "1", false },
            { "True", true },
            { "False", true },
            { "true", true },
            { "false", true },
            { "Yes", false },
            { "No", false },
#elif ConversionExtensionsTestsDataSource_Guid
            { Min_Guid.ToString(), true },
            { Max_Guid.ToString(), true },
            { Guid1.ToString(), true },
            { Guid2.ToString(), true },
            { Guid.Empty.ToString(), true },
            { nameof(Guid), false },
#else
            { decimal.MinValue.ToString(), true },
            { decimal.MaxValue.ToString(), true },
            { "0", true },
            { "1", true },
            { "-1", IsSigned },
            { "100", true },
            { "-100", IsSigned },
            { " 100", true },
            { "100 ", true },
            { "1.5", HasDecimalPlaces },
            { "£100", false },
#endif
        };
    }

    public static TheoryData<string, decimal> ToDecimal()
    {
        return new TheoryData<string, decimal>()
        {
#if ConversionExtensionsTestsDataSource_Bool
            { "True", true },
            { "False", false },
            { "true", true },
            { "false", false },
#elif ConversionExtensionsTestsDataSource_Guid
            { Guid.Empty.ToString(), Min_Guid },
            { Guid.Empty.ToString().Replace("0", "F"), Max_Guid },
            { Guid1.ToString(), Guid1 },
            { Guid2.ToString(), Guid2 },
#else
            { decimal.MinValue.ToString(), decimal.MinValue },
            { decimal.MaxValue.ToString(), decimal.MaxValue },
            { "0", 0 },
            { "100", 100 },
            { "10", 10 },
            { "10 ", 10 },
#endif
        };
    }

    public static TheoryData<string, bool> ToDecimalThrows()
    {
        return new TheoryData<string, bool>()
        {
#if ConversionExtensionsTestsDataSource_Bool
            { "0", false },
            { "1", false },
            { "false", true },
            { "true", true },
#elif ConversionExtensionsTestsDataSource_Guid
            { "0", false },
            { "1", false },
            { Guid2.ToString(), true },
#else
            { "abcdef", false },
            { "1,000", HasDecimalPlaces },
            { new BigInteger(decimal.MaxValue).ToString(), true },
            { (new BigInteger(decimal.MaxValue) + 1).ToString(), !UsesExponentApproximations },
#endif
        };
    }

    public static TheoryData<string, decimal, decimal> ToDecimalWithDefault()
    {
        return new TheoryData<string, decimal, decimal>()
        {
#if ConversionExtensionsTestsDataSource_Bool
            { "abcdef", false, false },
            { "Negatory", true, true },
            { "Affirmative", false, false },
            { "false", true, false },
#elif ConversionExtensionsTestsDataSource_Guid
            { "abcdef", Guid1, Guid1 },
            { Max_Guid.ToString(), Min_Guid, Max_Guid },
#else
            { "abcdef", (decimal)25, 25 },
            { "50.5", (decimal)25, HasDecimalPlaces ? CreateValue("50.5") : (decimal)25 },
            { "100,000", (decimal)100, HasDecimalPlaces ? (decimal)(new BigInteger(100000)) : (decimal)100 },
            { "100", (decimal)25, 100 },
#endif
        };
    }
}

