//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

using DNX.Extensions.Converters.BuiltInTypes;
using DNX.Extensions.Exceptions;
using DNX.Extensions.Tests.Conversion.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

namespace DNX.Extensions.Tests.Conversion.BuiltInTypes;

public class ConversionGuidExtensionsTests
{
    [Theory]
    [MemberData(nameof(ConversionGuidExtensionsTestsDataSource.IsGuid), MemberType = typeof(ConversionGuidExtensionsTestsDataSource))]
    public void Test_IsGuid(string text, bool expectedResult)
    {
        var result = text.IsGuid();

        result.ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(ConversionGuidExtensionsTestsDataSource.ToGuid), MemberType = typeof(ConversionGuidExtensionsTestsDataSource))]
    public void Test_ToGuid(string text, Guid expectedResult)
    {
        var result = text.ToGuid();

        result.ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(ConversionGuidExtensionsTestsDataSource.ToGuidThrows), MemberType = typeof(ConversionGuidExtensionsTestsDataSource))]
    public void Test_ToGuid_Throws(string text, bool expectedResult)
    {
        try
        {
            text.ToGuid();

            expectedResult.ShouldBeTrue();
        }
        catch (ConversionException ex)
        {
            ex.Value.ShouldBe(text);

            expectedResult.ShouldBeFalse();
        }
    }

    [Theory]
    [MemberData(nameof(ConversionGuidExtensionsTestsDataSource.ToGuidWithDefault), MemberType = typeof(ConversionGuidExtensionsTestsDataSource))]
    public void Test_ToGuid_with_default(string text, Guid defaultValue, Guid expectedResult)
    {
        var result = text.ToGuid(defaultValue);

        result.ShouldBe(expectedResult);
    }
}

