//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

using DNX.Extensions.Converters.BuiltInTypes;
using DNX.Extensions.Exceptions;
using DNX.Extensions.Tests.Conversion.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

namespace DNX.Extensions.Tests.Conversion.BuiltInTypes;

public class ConversionByteExtensionsTests
{
    [Theory]
    [MemberData(nameof(ConversionByteExtensionsTestsDataSource.IsByte), MemberType = typeof(ConversionByteExtensionsTestsDataSource))]
    public void Test_IsByte(string text, bool expectedResult)
    {
        var result = text.IsByte();

        result.ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(ConversionByteExtensionsTestsDataSource.ToByte), MemberType = typeof(ConversionByteExtensionsTestsDataSource))]
    public void Test_ToByte(string text, byte expectedResult)
    {
        var result = text.ToByte();

        result.ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(ConversionByteExtensionsTestsDataSource.ToByteThrows), MemberType = typeof(ConversionByteExtensionsTestsDataSource))]
    public void Test_ToByte_Throws(string text, bool expectedResult)
    {
        try
        {
            text.ToByte();

            expectedResult.ShouldBeTrue();
        }
        catch (ConversionException ex)
        {
            ex.Value.ShouldBe(text);

            expectedResult.ShouldBeFalse();
        }
    }

    [Theory]
    [MemberData(nameof(ConversionByteExtensionsTestsDataSource.ToByteWithDefault), MemberType = typeof(ConversionByteExtensionsTestsDataSource))]
    public void Test_ToByte_with_default(string text, byte defaultValue, byte expectedResult)
    {
        var result = text.ToByte(defaultValue);

        result.ShouldBe(expectedResult);
    }
}

