//==============================================================================
// This source file was generated by a script - do not edit manually
//==============================================================================

using DNX.Extensions.Converters.BuiltInTypes;
using DNX.Extensions.Exceptions;
using DNX.Extensions.Tests.Conversion.BuiltInTypes.TestsDataSource;
using Shouldly;
using Xunit;

namespace DNX.Extensions.Tests.Conversion.BuiltInTypes;

public class ConversionSByteExtensionsTests
{
    [Theory]
    [MemberData(nameof(ConversionSByteExtensionsTestsDataSource.IsSByte), MemberType = typeof(ConversionSByteExtensionsTestsDataSource))]
    public void Test_IsSByte(string text, bool expectedResult)
    {
        var result = text.IsSByte();

        result.ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(ConversionSByteExtensionsTestsDataSource.ToSByte), MemberType = typeof(ConversionSByteExtensionsTestsDataSource))]
    public void Test_ToSByte(string text, sbyte expectedResult)
    {
        var result = text.ToSByte();

        result.ShouldBe(expectedResult);
    }

    [Theory]
    [MemberData(nameof(ConversionSByteExtensionsTestsDataSource.ToSByteThrows), MemberType = typeof(ConversionSByteExtensionsTestsDataSource))]
    public void Test_ToSByte_Throws(string text, bool expectedResult)
    {
        try
        {
            text.ToSByte();

            expectedResult.ShouldBeTrue();
        }
        catch (ConversionException ex)
        {
            ex.Value.ShouldBe(text);

            expectedResult.ShouldBeFalse();
        }
    }

    [Theory]
    [MemberData(nameof(ConversionSByteExtensionsTestsDataSource.ToSByteWithDefault), MemberType = typeof(ConversionSByteExtensionsTestsDataSource))]
    public void Test_ToSByte_with_default(string text, sbyte defaultValue, sbyte expectedResult)
    {
        var result = text.ToSByte(defaultValue);

        result.ShouldBe(expectedResult);
    }
}

