name: CI Build
run-name: CIBuild_${{ github.ref_name }}

env:
  BUILD_CONFIG: 'Release'
  BUILD_PLATFORM: 'Any CPU'
  PKG_VER: 1.0

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'task/**'
      - 'spike/**'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build .NET

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG /p:"Platform=$BUILD_PLATFORM" --no-restore

    - name: Test
      run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

  release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/heads/main')
  
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Tag git
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        tag_prefix: v
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}

  publish:
    name: Publish to NuGet
    if: startsWith(github.ref, 'refs/heads/main')

    needs: release
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '5.x'

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json'
