name: CI Build
run-name: CIBuild_${{ github.event_name }}_${{ github.ref_name }}_${{ github.run_number }}.${{ github.run_attempt }}

env:
  PROJECT_NAME: 'DNX.Extensions'
  PKG_MAJOR_VERSION: '1.0'
  DOTNET_VERSION: 6.0.x
  NUGET_VERSION: 5.x
  BUILD_CONFIG: Release
  BUILD_PLATFORM: Any CPU
  PACK_PARAMETERS: ''
  NUGET_OUTPUT_FOLDER: nupkgs

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'task/**'
      - 'spike/**'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build .NET

    runs-on: ubuntu-latest

    steps:
    - name: Set Product Version
      id: product_version
      run: echo "product_version=${{ env.PKG_MAJOR_VERSION }}" >> $GITHUB_ENV
      
    - name: Set Assembly Version
      id: assembly_version
      run: echo "assembly_version=${{ env.PKG_MAJOR_VERSION }}.${{ github.run_number }}.${{ github.run_attempt }}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.BUILD_CONFIG }} /p:"Platform=${{ env.BUILD_PLATFORM }}" /p:"Version=${{ env.product_version }}" /p:"AssemblyVersion=${{ env.assembly_version }}" --no-restore

    - name: Test
      run: dotnet test --configuration ${{ env.BUILD_CONFIG }} --no-restore --no-build --verbosity normal

    - name: Pack
      run: dotnet pack --configuration ${{ env.BUILD_CONFIG }} /p:"Platform=${{ env.BUILD_PLATFORM }}" /p:"Version=${{ env.product_version }}" /p:"AssemblyVersion=${{ env.assembly_version }}" --no-restore --output "${{ env.NUGET_OUTPUT_FOLDER }}"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build_output
        path: "**/${{ env.PROJECT_NAME }}/bin/${{ env.BUILD_CONFIG }}/**"
        if-no-files-found: error

    - name: Upload NuGet  Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nuget_output
        path: "${{ env.NUGET_OUTPUT_FOLDER }}/**"
        if-no-files-found: error

  release:
    name: Create GitHub Release
    if: github.ref == 'refs/heads/main' && success()
  
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Tag git
      uses: pkgdeps/git-tag-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_repo: ${{ github.repository }}
        git_commit_sha: ${{ github.sha }}
        version: "${{ env.assembly_version }}"
        git_tag_prefix: "v"    

    - name: Build git Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v3.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ env.assembly_version }}
        name: Release ${{ env.assembly_version }}
        body: ${{ steps.build_changelog.outputs.changelog }}

  publish:
    name: Publish to NuGet
    if: github.ref == 'refs/heads/main' && success()

    needs: release
    
    runs-on: ubuntu-latest

    steps:
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: ${{ env.NUGET_VERSION }}

    - name: Download NuGet Output
      id: download_nuget
      uses: actions/download-artifact@v3
      with:
        name: nuget_output
        path: ${{ env.NUGET_OUTPUT_FOLDER }}

    - name: Publish
      run: nuget push "$${{steps.download_nuget.outputs.download-path}}/**/*.nupkg" -Source 'https://api.nuget.org/v3/index.json'
